server:
  port: 9000

spring:
  application:
    name: UserServer
  data:
    mongodb:
      authentication-database: admin
      database: test
      host: localhost
      port: 27017
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
              
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
